print(" What is your name ? ")
a= input(" My name is : ")
print("Right answer")
print(" What is your brother name ?")
b= input("Name : ")
print(" Enter the first number : ")
c= input()
print("Enter the second number : ")
d= input()
print("The addition of that two number is : ",int(c)+int(d))
print("The addition of that two number is :",c+d)
print(a[2])
