import cv2 as cv
img = cv.imread("WIN_20221105_21_12_17_Pro.jpg")
cv.imshow('Jeet',img)
print("the shape of the image is : ")
print(img.shape)
print("the size of the image is : ")
print(img.size)
img_grey= cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow('Jeet_grey',img_grey)
print("The shepe and size of the image is after convert to grey is",img_grey.shape,img_grey.size)
img_hsv = cv.cvtColor(img,cv.COLOR_BGR2HSV)
cv.imshow('Jeet',img_hsv)
print("The size and the shape of the image is after turn in to hsv ",img_hsv.size,img_hsv.shape)
cv.waitKey(0)
cv.destroyAllWindows()
